/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'itemCount' : IDL.Text,
  'message' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const MovementQuote = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'fromAddress' : IDL.Text,
  'createdAt' : IDL.Int,
  'items' : IDL.Text,
  'estimatedDate' : IDL.Text,
  'toAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  'addContactRequest' : IDL.Func([Contact], [IDL.Bool], []),
  'addMovementQuote' : IDL.Func([MovementQuote], [IDL.Bool], []),
  'getContactRequests' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getMovementQuotes' : IDL.Func([], [IDL.Vec(MovementQuote)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'itemCount' : IDL.Text,
    'message' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MovementQuote = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'fromAddress' : IDL.Text,
    'createdAt' : IDL.Int,
    'items' : IDL.Text,
    'estimatedDate' : IDL.Text,
    'toAddress' : IDL.Text,
  });
  
  return IDL.Service({
    'addContactRequest' : IDL.Func([Contact], [IDL.Bool], []),
    'addMovementQuote' : IDL.Func([MovementQuote], [IDL.Bool], []),
    'getContactRequests' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getMovementQuotes' : IDL.Func([], [IDL.Vec(MovementQuote)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };